from solution import Point, Segment, CoordinateSystem

p1 = Point((-2, 7))
print(p1)
p2 = Point((3, 4))
s1 = Segment(p1, p2)
print(s1)
print(s1.one_intersection)
xy = CoordinateSystem()
xy.add_segment(s1)
p3 = Point((2, -8))
p4 = Point((4, 16))
s2 = Segment(p3, p4)
xy.add_segment(s2)
xy.add_segment(Segment(p4, p2))
xy.add_segment(Segment(Point((-5, 3)), Point((-13, -6))))
print(xy.segments)
print(xy)
print(xy.axis_intersection())